F:\toolkithelper.exe G:\MOUNT GameExplorer
F:\toolkithelper.exe G:\MOUNT SnippingTool
F:\toolkithelper.exe G:\MOUNT SpeechRecognition
F:\toolkithelper.exe G:\MOUNT WindowsMediaPlayer
F:\toolkithelper.exe G:\MOUNT WinSAT
F:\toolkithelper.exe G:\MOUNT AssignedAccess
F:\toolkithelper.exe G:\MOUNT CEIP_SQM
F:\toolkithelper.exe G:\MOUNT KernelDebugging
F:\toolkithelper.exe G:\MOUNT LocationService
F:\toolkithelper.exe G:\MOUNT UnifiedTelemetryClient
F:\toolkithelper.exe G:\MOUNT WindowsErrorReporting
F:\toolkithelper.exe G:\MOUNT WindowsInsiderHub
F:\toolkithelper.exe G:\MOUNT HomeGroup
F:\toolkithelper.exe G:\MOUNT MultiPointConnector
F:\toolkithelper.exe G:\MOUNT RemoteAssistance
F:\toolkithelper.exe G:\MOUNT DeviceLockdown
F:\toolkithelper.exe G:\MOUNT EaseOfAccessThemes
F:\toolkithelper.exe G:\MOUNT Paint
F:\toolkithelper.exe G:\MOUNT SecurityCenter
F:\toolkithelper.exe G:\MOUNT SystemRestore
F:\toolkithelper.exe G:\MOUNT WindowsToGo
F:\toolkithelper.exe G:\MOUNT AADBrokerPlugin
F:\toolkithelper.exe G:\MOUNT AssignedAccessLockApp
F:\toolkithelper.exe G:\MOUNT CBSPreview
F:\toolkithelper.exe G:\MOUNT ContentDeliveryManager
F:\toolkithelper.exe G:\MOUNT Cortana
F:\toolkithelper.exe G:\MOUNT ECApp
F:\toolkithelper.exe G:\MOUNT EdgeDevToolsClient
F:\toolkithelper.exe G:\MOUNT Edge
F:\toolkithelper.exe G:\MOUNT MapControl
F:\toolkithelper.exe G:\MOUNT OneDrive
F:\toolkithelper.exe G:\MOUNT NarratorQuickStart
F:\toolkithelper.exe G:\MOUNT ParentalControls
F:\toolkithelper.exe G:\MOUNT PeopleExperienceHost
F:\toolkithelper.exe G:\MOUNT PPIProjection
F:\toolkithelper.exe G:\MOUNT QuickAssist
F:\toolkithelper.exe G:\MOUNT RetailDemoContent
F:\toolkithelper.exe G:\MOUNT SecureAssessmentBrowser
F:\toolkithelper.exe G:\MOUNT SettingSync
F:\toolkithelper.exe G:\MOUNT SkypeORTC
F:\toolkithelper.exe G:\MOUNT SmartScreen
F:\toolkithelper.exe G:\MOUNT WindowsDefender
F:\toolkithelper.exe G:\MOUNT WindowsMixedReality
F:\toolkithelper.exe G:\MOUNT WindowsReaderPDF
F:\toolkithelper.exe G:\MOUNT XboxGameCallableUI
F:\toolkithelper.exe G:\MOUNT 3DViewer
F:\toolkithelper.exe G:\MOUNT AdvertisingXaml
F:\toolkithelper.exe G:\MOUNT Alarms
F:\toolkithelper.exe G:\MOUNT BingWeather
F:\toolkithelper.exe G:\MOUNT Calculator
F:\toolkithelper.exe G:\MOUNT CommunicationsApps
F:\toolkithelper.exe G:\MOUNT FeedbackHub
F:\toolkithelper.exe G:\MOUNT GetHelp
F:\toolkithelper.exe G:\MOUNT Getstarted
F:\toolkithelper.exe G:\MOUNT Maps
F:\toolkithelper.exe G:\MOUNT Messaging
F:\toolkithelper.exe G:\MOUNT MixedRealityPortal
F:\toolkithelper.exe G:\MOUNT OfficeHub
F:\toolkithelper.exe G:\MOUNT OfficeOneNote
F:\toolkithelper.exe G:\MOUNT OneConnect
F:\toolkithelper.exe G:\MOUNT Paint3D
F:\toolkithelper.exe G:\MOUNT People
F:\toolkithelper.exe G:\MOUNT Photos
F:\toolkithelper.exe G:\MOUNT Print3D
F:\toolkithelper.exe G:\MOUNT ScreenSketch
F:\toolkithelper.exe G:\MOUNT SkypeApp
F:\toolkithelper.exe G:\MOUNT SolitaireCollection
F:\toolkithelper.exe G:\MOUNT SoundRecorder
F:\toolkithelper.exe G:\MOUNT StickyNotes
F:\toolkithelper.exe G:\MOUNT WalletService
F:\toolkithelper.exe G:\MOUNT XboxApp
F:\toolkithelper.exe G:\MOUNT XboxIdentityProvider
F:\toolkithelper.exe G:\MOUNT YourPhone
F:\toolkithelper.exe G:\MOUNT ZuneMusic
F:\toolkithelper.exe G:\MOUNT ZuneVideo